Fix missing listPool
AY2021S2-CS2103T-W10-1/tp pull request #227
Opened 2021-04-09 08:29 UTC by ZechariahTan

* Add missing functionality to revert filtered pool list

2021-04-09 08:52 UTC, markmcwong reviewed
LGTM

2021-04-10 07:06 UTC, chewterence requested changes
almost LGTM, only a few minor documentation errors, changes to be made.

2021-04-10 07:06 UTC, chewterence commented on src/main/java/seedu/address/logic/commands/ListPoolCommand.java
> + * Lists all passengers in the address book to the user.
did you mean list all pools?

2021-04-10 07:06 UTC, chewterence commented on src/test/java/seedu/address/logic/commands/ListPoolCommandTest.java
> + * Contains integration tests (interaction with the Model) and unit tests for ListCommand.
did you mean ListPoolCommand

2021-04-10 13:28 UTC, JoelHo approved these changes
LGTM

2021-04-10 13:28 UTC, merged