Improve code quality
AY2021S2-CS2103T-W10-1/tp pull request #235
Opened 2021-04-09 18:41 UTC by JoelHo

2021-04-10 02:43 UTC, markmcwong reviewed
LGTM

2021-04-10 02:57 UTC, chewterence requested changes

2021-04-10 02:57 UTC, chewterence commented on src/test/java/seedu/address/logic/parser/PoolCommandParserTest.java
>          //        assertParseFailure(parser, NAME_DESC_BOB + PHONE_DESC_BOB + TRIPDAY_DESC_MONDAY
there still appears to be commented out code

2021-04-10 07:10 UTC, chewterence commented
LGTM

2021-04-10 07:10 UTC, chewterence commented
LGTM

2021-04-10 07:10 UTC, merged

2021-04-11 06:58 UTC, JoelHo commented
Closes #95