Improve help command
AY2021S2-CS2103T-W10-1/tp pull request #255
Opened 2021-04-11 06:59 UTC by ZechariahTan

Add command summary to help command window

2021-04-11 08:26 UTC, markmcwong commented
LGTM

2021-04-12 04:51 UTC, lyueyang commented
resolves #239

2021-04-12 04:53 UTC, lyueyang commented
resolves #236

2021-04-12 06:47 UTC, markmcwong approved these changes
LGTM

2021-04-12 07:59 UTC, JoelHo requested changes
Do minimally remove the magic literals in the FXML

2021-04-12 07:59 UTC, JoelHo commented on src/main/resources/view/HelpWindow.fxml
> +                                       <HelpTableEntry action="exit" format="exit" />
Perhaps having magic literals (especially in the FXML file) is not so good here

2021-04-12 07:59 UTC, JoelHo commented on src/main/java/seedu/address/ui/HelpTableEntry.java
> +public class HelpTableEntry {
I'm not sure having a wrapper class here is absolutely necessary?

2021-04-12 08:06 UTC, chewterence commented
merging this PR would mean that we should update the UG's help command too

2021-04-12 13:21 UTC, closed without merging